language: python

matrix:
    include:
        - python: 3.7
          env:
            - TOXENV=py37
            - END_TO_END=1
          dist: xenial          # required for Python >= 3.7

install:
    - travis_retry pip install virtualenv tox

script:
    - travis_retry tox
